### ISSUE TITLE
Repeating MMS in Sangoma Talk Mobile

### ISSUE THREAD

**Issue by jacobi766** [simontelephonics/smsconnector#63] opened 2024-11-05 17:23 UTC
Thank you for your work on this project. 

I believe there is a bug with the messages being sent to the Sangoma Talk mobile app. I am curious if anyone else can reproduce this issue or if (hopefully) I have a misconfiguration?

The issue occurs when the remote sender sends a MMS image to our number. We receive the image fine. However, if they send a text based SMS AFTER the MMS image, we continually receive a resend of the original MMS image that was sent previously. We never see the new SMS text, but repeatedly see the MMS image each time they respond with text. This can be fixed if we reply to the MMS with text. They receive our text, and their next text comes through fine, until we receive another MMS image. The issue ONLY starts if an image is sent from the cell carrier inbound to our SMS number. Also, the issue is also only present on the Sangoma Talk mobile app. When viewing the thread in UCP or Sangoma Desktop app, the thread is accurate and all replies can be seen.

**Comment by billsimon** [comment] 2024-11-05 17:28
Hi, please add to your issue:
* version of FreePBX
* version of SMS Connector
* provider(s) you are using for MMS/SMS
* version of Talk mobile app

**Comment by billsimon** [comment] 2024-11-05 18:59
I actually have this exact configuration in place in a production system (including telnyx) and will test here.

**Comment by billsimon** [comment] 2024-11-05 20:46
My findings:
* everything works correctly on Phone Desktop and UCP - same as your findings
* Mobile iOS app - MMS received fine
   * next inbound text - I get the same MMS image from before
   * next inbound text - I get the inbound text (but the previous text is missing)

So findings are a little different than yours, but I can confirm 100% that the first inbound SMS after an MMS is not getting displayed in the Talk mobile app.

I suspect a bug in the FreePBX commercial module responsible for providing SMS/MMS content to the mobile app, which is different than what the Desktop app and UCP use.

Looking at the records in the database,

**Comment by jacobi766** [comment] 2024-12-18 02:58
In my limited testing, this issue seems to be fixed for me after updating to SangomaConnect 16.0.47.31

**Comment by billsimon** [comment] 2024-12-18 14:46
Excellent! I will test today also.

On Dec 17, 2024, at 21:59, jacobi766 ***@***.***> wrote:

﻿

In my limited testing, this issue seems to be fixed for me after updating to SangomaConnect 16.0.47.31

**Comment by billsimon** [comment] 2024-12-18 18:37
Indeed, appears to be resolved in latest Sangoma Connect module.

**Closed by billsimon** 2024-12-18 18:37 UTC
